export const PLAYER_IMAGE_PATHS: Record<string, string> = {
  "Thibaut Courtois": "Porteros/Thibaut Courtois.png",
  "Alisson Becker": "Porteros/Alisson Becker.png",
  "Emiliano Martínez": "Porteros/Dibu Martínez.png",
  "Gianluigi Donnarumma": "Porteros/Gianluigi Donnarumma.png",
  "Mike Maignan": "Porteros/Mike Maignan.png",
  "Ederson Moraes": "Porteros/Ederson Moraes.png",
  "Jan Oblak": "Porteros/Jan Oblak.png",
  "Giorgi Mamardashvili": "Porteros/Giorgi Mamardashvili.png",
  "Unai Simón": "Porteros/Unai Simón.png",
  "Guillermo Ochoa": "Porteros/Guillermo Ochoa.png",
  "Achraf Hakimi": "Lateral Derecho/Achraf Hakimi.png",
  "Trent Alexander-Arnold": "Lateral Derecho/Trent Alexander-Arnold.png",
  "Jeremie Frimpong": "Lateral Derecho/Jeremie Frimpong.png",
  "Jules Koundé": "Lateral Derecho/Jules Koundé.png",
  "Diogo Dalot": "Lateral Derecho/Diogo Dalot.png",
  "Josip Stanišić": "Lateral Derecho/Josip Stanišić.png",
  "Jorge Sánchez": "Lateral Derecho/Jorge Sánchez.png",
  "Rúben Dias": "Defensa Central 1/Rúben Dias.png",
  "William Saliba": "Defensa Central 1/William Saliba.png",
  "Antonio Rüdiger": "Defensa Central 1/Antonio Rüdiger.png",
  "Ronald Araújo": "Defensa Central 1/Ronald Araújo.png",
  "Johan Vásquez": "Defensa Central 1/Johan Vásquez.png",
  "Éder Militão": "Defensa Central 2/Éder Militão.png",
  "Joško Gvardiol": "Defensa Central 2/Joško Gvardiol .png",
  "Matthijs de Ligt": "Defensa Central 2/Matthijs de Ligt.png",
  "Cristian Romero": "Defensa Central 2/Cuti Romero.png",
  "Gleison Bremer": "Defensa Central 2/Gleison Bremer.png",
  "Gonçalo Inácio": "Defensa Central 2/Gonçalo Inácio.png",
  "César Montes": "Defensa Central 2/César Montes.png",
  "Theo Hernández": "Lateral Izquierdo/Theo Hernández.png",
  "Alphonso Davies": "Lateral Izquierdo/Alphonso Davies.png",
  "Alejandro Grimaldo": "Lateral Izquierdo/Alejandro Grimaldo.png",
  "Nuno Mendes": "Lateral Izquierdo/Nuno Mendes.png",
  "Mateo Chávez": "Lateral Izquierdo/Mateo Chávez.png",
  "Rodri Hernández": "Mediocentro Defensivo/Rodri Hernandez.png",
  "Declan Rice": "Mediocentro Defensivo/declan rice.png",
  "Aurélien Tchouaméni": "Mediocentro Defensivo/Aurélien Tchouaméni .png",
  "Eduardo Camavinga": "Mediocentro Defensivo/Eduardo Camavinga.png",
  "Bruno Guimarães": "Mediocentro Defensivo/Bruno Guimarães.png",
  "Manuel Ugarte": "Mediocentro Defensivo/Manuel Ugarte.png",
  "Edson Álvarez": "Mediocentro Defensivo/Edson Álvarez.png",
  "Jude Bellingham": "Mediocampista Central/Jude Bellingham.png",
  "Federico Valverde": "Mediocampista Central/Federico Valverde.png",
  "Pedri": "Mediocampista Central/Pedri.png",
  "Enzo Fernández": "Mediocampista Central/Enzo Fernández.png",
  "Vitinha": "Mediocampista Central/Vitinha.png",
  "Luis Chávez": "Mediocampista Central/Luis Chávez.png",
  "Florian Wirtz": "Mediocampista Ofensivo/Florian Wirtz.png",
  "Jamal Musiala": "Mediocampista Ofensivo/Jamal Musiala.png",
  "Martin Ødegaard": "Mediocampista Ofensivo/Martin Ødegaard.png",
  "Gilberto Mora": "Mediocampista Ofensivo/Gilberto Mora.png",
  "Lionel Messi": "Extremo Derecho/Lionel Messi.png",
  "Lamine Yamal": "Extremo Derecho/Lamine Yamal.png",
  "Bukayo Saka": "Extremo Derecho/Bukayo Saka.png",
  "Ousmane Dembélé": "Extremo Derecho/Ousmane Dembélé.png",
  "Johan Bakayoko": "Extremo Derecho/Johan Bakayoko.png",
  "Roberto Alvarado": "Extremo Derecho/Roberto Alvarado.png",
  "Erling Haaland": "Delantero Centro/Erling Haaland.png",
  "Kylian Mbappé": "Delantero Centro/Kylian Mbappé.png",
  "Harry Kane": "Delantero Centro/Harry Kane.png",
  "Cristiano Ronaldo": "Delantero Centro/Cristiano Ronaldo.png",
  "Armando González": "Delantero Centro/Armando González.png",
  "Vinícius Júnior": "Extremo Izquierdo/Vinícius Júnior.png",
  "Neymar Jr.": "Extremo Izquierdo/Neymar Jr..png",
  "Rafael Leão": "Extremo Izquierdo/Rafael Leão.png",
  "Luis Díaz": "Extremo Izquierdo/Luis Díaz.png",
  "Nico Williams": "Extremo Izquierdo/Nico Williams.png",
  "César Huerta": "Extremo Izquierdo/César Huerta.png",
}
