/** Selección nacional de cada jugador del roster (para fotos en uniforme). */
export const TICKET_PLAYER_NATIONS: Record<string, string> = {
  'Thibaut Courtois': 'Belgium',
  'Alisson Becker': 'Brazil',
  'Emiliano Martínez': 'Argentina',
  'Gianluigi Donnarumma': 'Italy',
  'Mike Maignan': 'France',
  'Ederson Moraes': 'Brazil',
  'Jan Oblak': 'Slovenia',
  'Giorgi Mamardashvili': 'Georgia',
  'Unai Simón': 'Spain',
  'Guillermo Ochoa': 'Mexico',
  'Achraf Hakimi': 'Morocco',
  'Trent Alexander-Arnold': 'England',
  'Jeremie Frimpong': 'Netherlands',
  'Jules Koundé': 'France',
  'Diogo Dalot': 'Portugal',
  'Josip Stanišić': 'Croatia',
  'Jorge Sánchez': 'Mexico',
  'Rúben Dias': 'Portugal',
  'William Saliba': 'France',
  'Antonio Rüdiger': 'Germany',
  'Ronald Araújo': 'Uruguay',
  'Johan Vásquez': 'Mexico',
  'Éder Militão': 'Brazil',
  'Joško Gvardiol': 'Croatia',
  'Matthijs de Ligt': 'Netherlands',
  'Cristian Romero': 'Argentina',
  'Gleison Bremer': 'Brazil',
  'Gonçalo Inácio': 'Portugal',
  'César Montes': 'Mexico',
  'Theo Hernández': 'France',
  'Alphonso Davies': 'Canada',
  'Alejandro Grimaldo': 'Spain',
  'Nuno Mendes': 'Portugal',
  'Mateo Chávez': 'Mexico',
  'Rodri Hernández': 'Spain',
  'Declan Rice': 'England',
  'Aurélien Tchouaméni': 'France',
  'Eduardo Camavinga': 'France',
  'Bruno Guimarães': 'Brazil',
  'Manuel Ugarte': 'Uruguay',
  'Edson Álvarez': 'Mexico',
  'Jude Bellingham': 'England',
  'Federico Valverde': 'Uruguay',
  Pedri: 'Spain',
  'Enzo Fernández': 'Argentina',
  Vitinha: 'Portugal',
  'Luis Chávez': 'Mexico',
  'Florian Wirtz': 'Germany',
  'Jamal Musiala': 'Germany',
  'Martin Ødegaard': 'Norway',
  'Gilberto Mora': 'Mexico',
  'Lionel Messi': 'Argentina',
  'Lamine Yamal': 'Spain',
  'Bukayo Saka': 'England',
  'Ousmane Dembélé': 'France',
  'Johan Bakayoko': 'Belgium',
  'Roberto Alvarado': 'Mexico',
  'Erling Haaland': 'Norway',
  'Kylian Mbappé': 'France',
  'Harry Kane': 'England',
  'Cristiano Ronaldo': 'Portugal',
  'Armando González': 'Mexico',
  'Vinícius Júnior': 'Brazil',
  'Neymar Jr.': 'Brazil',
  'Rafael Leão': 'Portugal',
  'Luis Díaz': 'Colombia',
  'Nico Williams': 'Spain',
  'César Huerta': 'Mexico',
}

export function getTicketPlayerNation(playerName: string): string | undefined {
  return TICKET_PLAYER_NATIONS[playerName]
}
